# debug or release
runMod: debug

mysql:
  Host: 172.17.0.1
  Port: 3306
  Username: root
  Password: 654321!@#
  Database: go-tp

redis:
  Host: 172.17.0.1
  Port: 6379
  Password: 654321!@#
  Db: 1

logs:
  Path: ./tmp/

device:
  Cpu: 